require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Challenge' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'ChallengeTests' do
    inherit! :complete
  end

  $ReactNativeMapboxGLIOSVersion = '6.2.1'

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end

  post_install do |installer|
    react_native_post_install(installer)

    $RNMBGL.post_install(installer)

    # Fixes issue where on ARM-based Macs, Xcode builds targeted for the Simulator
    # fail because the arm64 architecture is unsupported. 'Debug' corresponds to
    # the configuration set in Xcode > TruckMap project > Info tab > Configurations.
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end